Upload second homework
webml/music-app pull request #2
Opened 2022-09-14 14:04 UTC by webml

2022-09-15 06:04 UTC, mrerberg requested changes

2022-09-15 06:04 UTC, mrerberg commented on src/components/Filter/Filter.css
> +  background: url('../../../public/img/icon/radio_disable.png') 0 0 no-repeat;
А разве не /public/img/icon/radio_disable.png?

2022-09-15 06:04 UTC, mrerberg commented on src/components/Sidebar/Sidebar.jsx
>  import './Sidebar.css'
Мб index.jsx?

2022-09-15 06:04 UTC, mrerberg commented on src/components/TrackSkeleton/index.jsx
> +      <use xlinkHref="img/skeleton/track.svg#track"></use>
Давай без use, вставь сюда разметку иконки

2022-09-15 15:53 UTC, webml commented on src/components/Filter/Filter.css
> +  background: url('../../../public/img/icon/radio_disable.png') 0 0 no-repeat;
В таком варианте отлично работает. Но как вариант можно заменить на /img/icon/radio_disable.png в других блоках вроде так работает.

2022-09-15 15:54 UTC, webml commented on src/components/Sidebar/Sidebar.jsx
>  import './Sidebar.css'
Да, сейчас в дз по стилям все компоненты переписываю на index

2022-09-15 15:55 UTC, webml commented on src/components/TrackSkeleton/index.jsx
> +      <use xlinkHref="img/skeleton/track.svg#track"></use>
Хорошо

2022-09-16 06:46 UTC, mrerberg commented on src/components/Filter/Filter.css
> +  background: url('../../../public/img/icon/radio_disable.png') 0 0 no-repeat;
Можно и так, главное, что путь короче был

2022-09-16 06:48 UTC, mrerberg requested changes

2022-09-16 06:48 UTC, mrerberg commented on src/components/TrackSkeleton/index.jsx
> +      <use xlinkHref="img/skeleton/track.svg#track"></use>
А ты запушил свежие коммиты?

2022-09-19 00:36 UTC, merged